### ISSUE TITLE
Failed to create symlink

### ISSUE THREAD

**Issue by JelmerD** [hendrikmaus/drafter-installer#1]
I am trying to install drafter using your installer, I performed all the steps and I am trying to install drafter v3.2.2.

But get an error right after the building process:

> Failed to create symbolic link from "/var/www/vendor/apiaryio/drafter/bin/drafter" to "/var/www/vendor/bin/drafter".

So https://github.com/hendrikmaus/drafter-installer/blob/master/src/Installer.php#L84 seems to be failing.

FYI:

The Drafter itself is working, by just specifying the absolute path to the apiaryio directory.

```php
$drafter = new Drafter(ROOT . '/vendor/apiaryio/drafter/bin/drafter');
```

My platform:

- Vagrant with bento/debian-8.6
- PHP 7.0.14-1~dotdeb+8.1

**Comment by deleugpn** [comment]
Facing this issue as well, but when I look for `apiaryio/drafter/bin`, the folder doesn't even exist.

**Comment by hendrikmaus** [comment]
@JelmerD @deleugpn I added a test with the latest drafter version and cannot reproduce your issue (https://travis-ci.org/hendrikmaus/drafter-installer/builds/401411758)

**Comment by startupengine** [comment]
I'm also dealing with this issue when using the installer with a Docker container. Might be a permission issue, because it works when I install normally.

**Comment by fulopattila122** [comment]
In our case works with Docker (`FROM php:7.3-fpm`) but fails on Vagrant (`debian/stretch64 9.8`)
