### ISSUE TITLE
vendor/bin/drafter not found

### ISSUE THREAD

**Issue by s2925534** [hendrikmaus/drafter-installer#2]
I am trying to install this but the dependency file that suppose to be created under the bin folder is  not being created.

Exception {#1416 ▼
  #message: "sh: 1: /var/www/portal/vendor/bin/drafter: not found\n"
  #code: 0
  #file: "/var/www/portal/vendor/hmaus/drafter-php/src/Drafter.php"
  #line: 165
  trace: {▼
    /var/www/portal/vendor/hmaus/drafter-php/src/Drafter.php:165 {▶}
    /var/www/portal/vendor/m165437/laravel-blueprint-docs/src/BlueprintDocs.php:59 {▶}
    /var/www/portal/app/Http/Controllers/ApiDocumentationController.php:28 {▼
      ›             $api = $blueprintDocs
      ›                 ->parse(config('blueprintdocs.blueprint_file'))
      › //            ->parse(config('blueprintdocs.blueprint_file'))
      arguments: {▶}
    }

**Comment by M165437** [comment]
Are you sure you included the script in your composer.json correctly?

```
"scripts": {
    "install-drafter": "Hmaus\\Drafter\\Installer::installDrafter"
}
```

If so, you can either run the script manually with `composer run-script install-drafter` or (if you also included the post-install-cmd and post-update-cmd references) by running `composer install` or `composer update`.

**Comment by hendrikmaus** [comment]
In addition to @M165437, we added a test case with an [example composer.json](https://github.com/hendrikmaus/drafter-installer/blob/master/test/composer.json) file.

Here is a test run using it:
https://travis-ci.org/hendrikmaus/drafter-installer/builds/401411758

**Comment by aolley** [comment]
I'm guessing this is related to the flavour of linux as I've reproduced this issue in Alpine:

```
/var/www/vendor/apiaryio/drafter/bin # cat /etc/alpine-release
3.7.0

/var/www/vendor/apiaryio/drafter/bin # ls -l
total 4676
-rwxr-xr-x    1 root     root       4785728 Oct 22 12:49 drafter

/var/www/vendor/apiaryio/drafter/bin # ./drafter
sh: ./drafter: not found
```

But the exact same build steps have it work fine under Ubuntu.

**Comment by M165437** [comment]
Hi aolley, have a look at the installer script. [Line 125](https://github.com/hendrikmaus/drafter-installer/blob/master/src/Installer.php#L125) determines the OS via php_uname(). Do you know what php_uname() returns on Alpine?

**Comment by aolley** [comment]
I went to reply on this shortly after I posted that comment - but github wasn't showing it - so I wasn't sure it had posted at all. Glitch in the matrix I suppose.

So my problem was actually what I suspect @s2925534 's problem was - my build process was accidentally including the Ubuntu built binary - which doesn't work on Alpine. After correcting my build to build the binary within Alpine - the binary works without any issues.

You can probably close this issue unless @s2925534 can confirm they built the binary on actual target system and didn't accidentally copy it from a different one.

**Comment by hendrikmaus** [comment]
Thanks for following up on this. My next guess would have been some glibc dependency which is tricky to solve when trying to compile in Alpine. 

GitHub had an incident yesterday which caused your issue with the comment.
