### ISSUE TITLE
vendor/apiaryio/drafter/bin not found on Debian 9.8

### ISSUE THREAD

**Issue by fulopattila122** [hendrikmaus/drafter-installer#5]
Looks like this is related to #1 #2 #4
 
In our case we're attempting to run it within Vagrant with `debian/stretch64` (Debian 9.8).

It runs without warnings:

```
vagrant@stretch:/var/www/vhosts/project.xyz$ composer install-drafter
> Hmaus\Drafter\Installer::installDrafter
  - Installing apiaryio/drafter (v3.2.7): Cloning v3.2.7 from cache
    Fetching submodules
    Compiling drafter (grab a coffee | -v for output)
```
The symlinks in `vendor/bin` gets created, but the folder `vendor/bin/apiaryio/drafter/bin` for the target is missing.

Is there anything we could try?
Please let me know if there's any additional Information I could provide with.

Thank you

**Comment by fulopattila122** [comment]
Got the problem: there were some tools missing from the OS.

To solve it, install the `build-essential` package:

```bash
sudo apt install build-essential
```

**Comment by andrewmclagan** [comment]
what about alpine linux?

**Comment by hendrikmaus** [comment]
@andrewmclagan you can refer to the upstream [Dockerfile](https://github.com/apiaryio/drafter/blob/master/Dockerfile), it is based on alpine https://github.com/apiaryio/drafter/blob/master/Dockerfile

**Comment by ezandonai** [comment]
I'm having a similar issue:

```bash
 $ docker compose exec php-fpm composer install-drafter -v
> install-drafter: Hmaus\Drafter\Installer::installDrafter
  - Syncing apiaryio/drafter (v5.0.0) into cache
    Fetching submodules
sh: 1: exec: git submodule update --init --checkout --recursive: not found
    Compiling drafter (grab a coffee | -v for output)
python ./configure
make: python: Command not found
make: *** [Makefile:60: config.gypi] Error 127
sh: 1: exec: chmod +x drafter: not found
```

**Comment by hendrikmaus** [comment]
Make sure you have all dependencies installed. Your logs suggest you are missing tools like Python.
